// Mocks generated by Mockito 5.4.6 from annotations
// in echofit/test/metrics_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:echofit/models/health_metric.dart' as _i5;
import 'package:echofit/services/database_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  set database(_i2.Database? db) => super.noSuchMethod(
    Invocation.setter(#database, db),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<int> insertMetric(_i5.HealthMetric? metric) =>
      (super.noSuchMethod(
            Invocation.method(#insertMetric, [metric]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.HealthMetric>> getAllMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMetrics, []),
            returnValue: _i4.Future<List<_i5.HealthMetric>>.value(
              <_i5.HealthMetric>[],
            ),
          )
          as _i4.Future<List<_i5.HealthMetric>>);

  @override
  _i4.Future<List<_i5.HealthMetric>> getUnsyncedMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedMetrics, []),
            returnValue: _i4.Future<List<_i5.HealthMetric>>.value(
              <_i5.HealthMetric>[],
            ),
          )
          as _i4.Future<List<_i5.HealthMetric>>);

  @override
  _i4.Future<void> updateMetric(_i5.HealthMetric? metric) =>
      (super.noSuchMethod(
            Invocation.method(#updateMetric, [metric]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMetric(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMetric, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
