// Mocks generated by Mockito 5.4.6 from annotations
// in echofit/test/metrics_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:echofit/models/health_metric.dart' as _i5;
import 'package:echofit/services/database_service.dart' as _i3;
import 'package:echofit/services/settings_service.dart' as _i6;
import 'package:echofit/services/sync_service.dart' as _i7;
import 'package:echofit/utils/backup_pruning_utils.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  set database(_i2.Database? db) => super.noSuchMethod(
    Invocation.setter(#database, db),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<int> insertMetric(_i5.HealthMetric? metric) =>
      (super.noSuchMethod(
            Invocation.method(#insertMetric, [metric]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.HealthMetric>> getAllMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMetrics, []),
            returnValue: _i4.Future<List<_i5.HealthMetric>>.value(
              <_i5.HealthMetric>[],
            ),
          )
          as _i4.Future<List<_i5.HealthMetric>>);

  @override
  _i4.Future<List<_i5.HealthMetric>> getUnsyncedMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedMetrics, []),
            returnValue: _i4.Future<List<_i5.HealthMetric>>.value(
              <_i5.HealthMetric>[],
            ),
          )
          as _i4.Future<List<_i5.HealthMetric>>);

  @override
  _i4.Future<void> updateMetric(_i5.HealthMetric? metric) =>
      (super.noSuchMethod(
            Invocation.method(#updateMetric, [metric]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMetric(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMetric, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i6.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveCredentials(String? url, String? user, String? pass) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [url, user, pass]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String?>> getCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#getCredentials, []),
            returnValue: _i4.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i4.Future<Map<String, String?>>);

  @override
  _i4.Future<bool> hasCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#hasCredentials, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i7.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> syncWithNextcloud({
    required String? baseUrl,
    required String? username,
    required String? appPassword,
    String? remotePath = 'EchoFit/data.json',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncWithNextcloud, [], {
              #baseUrl: baseUrl,
              #username: username,
              #appPassword: appPassword,
              #remotePath: remotePath,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.BackupFile>> listBackups(
    String? backupDirUrl,
    String? auth,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listBackups, [backupDirUrl, auth]),
            returnValue: _i4.Future<List<_i8.BackupFile>>.value(
              <_i8.BackupFile>[],
            ),
          )
          as _i4.Future<List<_i8.BackupFile>>);

  @override
  _i4.Future<List<_i8.BackupFile>> getAvailableBackups({
    required String? baseUrl,
    required String? username,
    required String? appPassword,
    String? remotePath = 'EchoFit/data.json',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableBackups, [], {
              #baseUrl: baseUrl,
              #username: username,
              #appPassword: appPassword,
              #remotePath: remotePath,
            }),
            returnValue: _i4.Future<List<_i8.BackupFile>>.value(
              <_i8.BackupFile>[],
            ),
          )
          as _i4.Future<List<_i8.BackupFile>>);

  @override
  _i4.Future<void> importFromBackup({
    required String? backupUrl,
    required String? username,
    required String? appPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importFromBackup, [], {
              #backupUrl: backupUrl,
              #username: username,
              #appPassword: appPassword,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
